Flownative:
  DoubleOptIn:
    presets:
      'upassist-neos-frontendlogin':
        # the length of the generated token, in bytes, before hex encoding
        tokenLength: 32
        # how long a token should be valid after generation, in seconds
        lifetime: 86400
        # if set to true, tokens are not removed from cache automatically when the activation link is called
        preserveToken: false
        # configuration for building an activation link for a token
        activation:
          # if uri is given as a string, it is used as given.
          # the placeholder -tokenhash- will be replaced with the token hash
          # uri: 'http://acme.com/activate/-tokenhash-'

          # if uri is a hash it is used as UriBuilder input (like in Routes.yaml)
          # the placeholder -tokenhash- will be replaced with the token hash in the built uri
          uri:
            '@package': 'UpAssist.Neos.FrontendLogin'
            '@subpackage': ~
            '@controller': 'User'
            '@format': 'html'
            '@action': 'ConfirmRegistration'
            arguments:
              'token': '-tokenhash-'
        mail:
          subject: 'Bitte bestätigen Sie das Newsletter Abonnement'
